
package cn.ijingxi.common.orm;

import java.lang.reflect.Field;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.*;

import cn.ijingxi.common.orm.ORM.KeyType;
import cn.ijingxi.common.util.IjxEnum;
import cn.ijingxi.common.util.LRU;
import cn.ijingxi.common.util.LinkNode;
import cn.ijingxi.common.util.jxCompare;
import cn.ijingxi.common.util.jxLink;
import cn.ijingxi.common.util.jxMsg;
import cn.ijingxi.common.util.utils;


public class jxORMobj
{
	private static Map<String,ORMClassAttr> ClassAttrTree=new HashMap<String,ORMClassAttr>();
	private static Map<String,IjxEnum> jxEnumTransor=new HashMap<String,IjxEnum>();

	private ORMClassAttr myClassAttr=null;
	private Queue<Object> params=null;
	
	private static LRU myLRU=new LRU();
	
	//加密处理，加密解密是发生在从数据库中读出与写入之时
	static String Encrypt(String str)
	{
		return str;
	}
	static Object EncryptField(FieldAttr fa,Object value)
	{
		if(value!=null&&fa.Encrypted&&value instanceof String)
			return Encrypt((String) value);
		return value;
	}
	static Object Encrypte(String className, String colName, Object value)
	{
		FieldAttr fa=getFieldAttr(className,colName);
		return EncryptField(fa,value);
	}
	static String DeEncrypt(String str)
	{
		return str;
	}
	static Object DeEncryptField(FieldAttr fa,Object value)
	{
		if(value!=null&&fa.Encrypted&&value instanceof String)
			return DeEncrypt((String) value);
		return value;
	}
	static Object DeEncrypte(String className, String colName, Object value)
	{
		FieldAttr fa=getFieldAttr(className,colName);
		return DeEncryptField(fa,value);
	}

	public ORMID getORMID() throws Exception
	{
		if(myClassAttr.PrimaryKeys!=null&&myClassAttr.PrimaryKeys.size()==1&&myClassAttr.PrimaryKeys.get(0)=="ID")
			return new ORMID(myClassAttr.ClsName,(Integer) utils.getFiledValue(this, "ID"));
		return null;
	}
	
	public static void AddEunmType(IjxEnum e)
	{
		jxEnumTransor.put(utils.GetClassName(e.getClass()), e);
	}
	public static Object TransTojxEunm(Class<?> cls,Object v)
	{
		IjxEnum e=jxEnumTransor.get(utils.GetClassName(cls));
		if(e!=null)
			return e.TransToORMEnum((Integer) v);
		return null;
	}
	
	
	public static void InitClass(Class<?> cls) throws Exception
	{
		Field[] fs = cls.getDeclaredFields();
		if(fs==null||fs.length==0)return;
		String classname=utils.GetClassName(cls);		
		ORMClassAttr attr=new ORMClassAttr();
		ClassAttrTree.put(classname, attr);
		attr.ClsName=classname;
		attr.clsType=cls;		
		
		for(Field f:fs)
		{
			String fn=f.getName();
			ORM ann = f.getAnnotation(ORM.class);
			if(ann!=null)
			{
				attr.DBTableName=Encrypt(classname);
				FieldAttr fa=new FieldAttr();
				fa.FieldType=f.getType();
				if(utils.JudgeIsEnum(fa.FieldType))
					fa.IsEnum=true;
				attr.Fields.put(fn, fa);
				fa.Encrypted=ann.Encrypted();
				if(ann.keyType()==KeyType.AutoGenerated)
				{
					fa.IsDBGenerateKey=true;
					fa.IsPrimaryKey=true;
					attr.DBGenerateKey=fn;
					if(attr.PrimaryKeys==null)
						attr.PrimaryKeys=new ArrayList<String>();
					attr.PrimaryKeys.add(fn);
				}
				else if(ann.keyType()==KeyType.PrimaryKey)
				{
					fa.IsPrimaryKey=true;
					if(attr.PrimaryKeys==null)
						attr.PrimaryKeys=new ArrayList<String>();
					attr.PrimaryKeys.add(fn);
				}
				if(ann.Index()>0)
				{
					if(attr.Indexs==null)
						attr.Indexs=new jxLink<Integer,ArrayList<String>>();
					ArrayList<String> iarr=attr.Indexs.search(ann.Index());
					if(iarr==null)
					{
						iarr=new ArrayList<String>();
						attr.Indexs.addByRise(ann.Index(), iarr);
					}
					iarr.add(fn);
				}
			}			
		}
		
		ORMClassAttr psa=getClassAttr(cls.getSuperclass());
		if(psa!=null)
			attr.SuperClassName=psa.ClsName;
	}
	public static jxORMobj New(Class<?> cls) throws Exception
	{
		String classname=utils.GetClassName(cls);
		ORMClassAttr attr=getClassAttr(classname);
		if(attr==null)return null;
		jxORMobj obj=(jxORMobj) cls.newInstance();
		obj.myClassAttr=attr;
		return obj;
	}
	
	static void DropTable(Class<?> cls) throws Exception
	{
		ORMClassAttr attr=getClassAttr(cls);
		if(attr==null||attr.DBTableName==null)return;
		DB db=JdbcUtils.GetDB();
		Connection conn = db.GetConnection();
		String sql="DROP TABLE "+attr.DBTableName;
		Exec(conn,sql,null);  	
		db.ReleaseConnection(conn);				
	}
	
	public static void CreateTableInDB(Class<?> cls) throws Exception
	{
		ORMClassAttr attr=getClassAttr(cls);
		if(attr==null||attr.DBTableName==null)return;
		try
		{
			//如果建表，则先试图将旧表删除
			DropTable(cls);
		}
		catch(Exception e){}
		
		DB db=JdbcUtils.GetDB();
		Connection conn = db.GetConnection();
		String cl=null;
		for(String fn:attr.Fields.keySet())
		{
			FieldAttr fa = attr.Fields.get(fn);
			cl=utils.StringAdd(cl, ",", fn+" "+db.TransDataTypeFromJavaToDB(fa.FieldType));
			if(fa.IsPrimaryKey&&attr.PrimaryKeys.size()==1)
			{
				cl+=" PRIMARY KEY";
				if(fa.IsDBGenerateKey)
					cl+=" "+db.GetDBGeneratedSQL();
			}
		}
		if(attr.PrimaryKeys.size()>1)
		{
			String ksl=null;
			for(String ks:attr.PrimaryKeys)
				ksl=utils.StringAdd(ksl, ",", ks);
			cl+=",PRIMARY KEY("+ksl+")";			
		}
		String sql="CREATE TABLE "+attr.DBTableName+"("+cl+")";
		Exec(conn,sql,null);  	
		if(attr.Indexs!=null)
		{
			for(LinkNode<Integer, ArrayList<String>> node:attr.Indexs)
			{
				String il=null;
				for(String index:node.getValue())
					il=utils.StringAdd(il, ",", index);
				sql="CREATE INDEX index_"+node.getKey()+"_"+attr.DBTableName+" ON "+attr.DBTableName+" ("+il+")";		
				Exec(conn,sql,null);  		
			}
		}
		db.ReleaseConnection(conn);		
	}
	
	
	//读写删插
	String GetWherePrimaryKey(DB db,Connection conn) throws Exception
	{
		if(myClassAttr.PrimaryKeys==null)return null;
		if(params==null)
			params=new LinkedList<Object>();
		String w=null;
		for(String s:myClassAttr.PrimaryKeys)
		{
			w=utils.StringAdd(w, " And ", s+"=?");
			params.offer(db.TransValueFromJavaToDB(jxORMobj.Encrypte(myClassAttr.ClsName, s, utils.getFiledValue(this, s))));			
		}
		return w;
	}
	//数据出数据库要做：
	//1、db数据类型到java数据类型的转换
	//2、解密
	public static Queue<jxORMobj> Select(Class<?> cls,SelectSql s) throws Exception
	{
		DB db=JdbcUtils.GetDB();
		Connection conn = db.GetConnection();
		Queue<jxORMobj> rs=Select(db,conn,cls,s);
		db.ReleaseConnection(conn);
		return rs;
	}
	public static Queue<jxORMobj> Select(DB db,Connection conn,Class<?> cls,SelectSql s) throws Exception
	{
		Queue<jxORMobj> rs=new LinkedList<jxORMobj>();
		String clsName=utils.GetClassName(cls);
		String sql = s.GetSql(clsName);
				
		PreparedStatement stmt = conn.prepareStatement(sql);
		int len=s.params.size();
		for(int i=1;i<=len;i++)
			stmt.setObject(i, s.params.poll());
		ResultSet result=stmt.executeQuery();
		ResultSetMetaData rsMetaData = result.getMetaData();
	    int numberOfColumns = rsMetaData.getColumnCount();
		while(result.next())
		{
			jxORMobj obj=New(cls);
			for(int i=1;i<=numberOfColumns;i++)
			{
				Object v =result.getObject(i);
				String cn=rsMetaData.getColumnName(i);
				FieldAttr fa = getFieldAttr(clsName,cn);
				
				Object dv=db.TransValueFromDBToJava(fa, v);
				Object ev=DeEncryptField(fa, dv);
				
				utils.setFiledValue(obj, cn, ev);
			}
			rs.offer(obj);
			myLRU.add(obj);
		}
		return rs;
	}
	public static jxORMobj Get(Class<?> cls,SelectSql s) throws Exception
	{
		DB db=JdbcUtils.GetDB();
		Connection conn = db.GetConnection();
		Queue<jxORMobj> rs=Select(db,conn,cls,s);
		db.ReleaseConnection(conn);
		return rs.poll();
	}
	public static jxORMobj GetByID(Class<?> cls,int ID) throws Exception
	{
		DB db=JdbcUtils.GetDB();
		Connection conn = db.GetConnection();
		jxORMobj obj=GetByID(db,conn,cls,ID);
		db.ReleaseConnection(conn);		
		return obj;
	}
	public static jxORMobj GetByID(String clsName,int ID) throws Exception
	{
		DB db=JdbcUtils.GetDB();
		Connection conn = db.GetConnection();
		ORMClassAttr attr = getClassAttr(clsName);
		SelectSql s=new SelectSql();
		s.AddTable(attr.ClsName);
		s.AddContion(attr.ClsName, attr.PrimaryKeys.get(0), jxCompare.Equal, ID);
		Queue<jxORMobj> rs=Select(db,conn,attr.clsType,s);
		db.ReleaseConnection(conn);		
		return rs.poll();
	}
	public static jxORMobj GetByID(DB db,Connection conn,Class<?> cls,int ID) throws Exception
	{
		ORMClassAttr attr = getClassAttr(cls);
		SelectSql s=new SelectSql();
		s.AddTable(attr.ClsName);
		s.AddContion(attr.ClsName, attr.PrimaryKeys.get(0), jxCompare.Equal, ID);
		Queue<jxORMobj> rs=Select(db,conn,cls,s);
		return rs.poll();
	}
	
	protected jxORMobj()
	{
		myInit();
	}
	//自动初始化
	protected void myInit()
	{
		
	}
	//数据校验
	protected void Verify() throws Exception
	{	
	}
	public void Update() throws Exception
	{
		DB db=JdbcUtils.GetDB();
		Connection conn = db.GetConnection();
        synchronized (this)
        {		
        	Update(db,conn);
        }
		db.ReleaseConnection(conn);		
	}
	//数据进数据库要做：
	//1、加密
	//2、java数据类型到db数据类型的转换
	public void Update(DB db,Connection conn) throws Exception
	{
		Verify();
		ORMClassAttr attr=myClassAttr;
		while(attr!=null)
		{
			if(attr.DBTableName!=null)
				Update(db,conn,attr);
			if(attr.SuperClassName!=null)
				attr=getClassAttr(attr.SuperClassName);
			else
				break;
		}		
	}
	private void Update(DB db,Connection conn,ORMClassAttr attr) throws Exception
	{
		if(params==null)
			params=new LinkedList<Object>();
		String sql="Update "+attr.DBTableName+" Set ";
		String v=null;
		for(String fn:attr.Fields.keySet())
		{
			v=utils.StringAdd(v, ",", fn+"=?");
			params.offer(db.TransValueFromJavaToDB(jxORMobj.Encrypte(attr.ClsName, fn, utils.getFiledValue(this, fn))));
		}
		sql+=v+" Where "+GetWherePrimaryKey(db,conn);
		Exec(conn,sql,params);
	}
	public void Delete() throws Exception
	{
		DB db=JdbcUtils.GetDB();
		Connection conn = db.GetConnection();
        synchronized (this)
        {		
        	Delete(db,conn);
        	myLRU.delete(getORMID());        	
        }
		db.ReleaseConnection(conn);		
	}
	public void Delete(DB db,Connection conn) throws Exception
	{
		ORMClassAttr attr=myClassAttr;
		while(attr!=null)
		{
			if(attr.DBTableName!=null)
				Delete(db,conn,attr);
			if(attr.SuperClassName!=null)
				attr=getClassAttr(attr.SuperClassName);
			else
				break;
		}		
	}
	private void Delete(DB db,Connection conn,ORMClassAttr attr) throws Exception
	{
		String sql="Delete From "+attr.DBTableName+" Where "+GetWherePrimaryKey(db,conn);
		Exec(conn,sql,params);
	}
	//数据进数据库要做：
	//1、加密
	//2、java数据类型到db数据类型的转换
	public Integer Insert() throws Exception
	{
		int id=0;
		DB db=JdbcUtils.GetDB();
		Connection conn = db.GetConnection();
        synchronized (this)
        {		
        	id=Insert(db,conn);
        	myLRU.add(this);
        }
		db.ReleaseConnection(conn);		
		return id;
	}
	public Integer Insert(DB db,Connection conn) throws Exception
	{
		Verify();
		//因为对象的id可能是自增长列，所以必须从最早的祖类开始插入
		Stack<ORMClassAttr> al=new Stack<ORMClassAttr>();
		ORMClassAttr attr=myClassAttr;
		while(attr!=null)
		{
			al.push(attr);
			if(attr.SuperClassName!=null)
				attr=getClassAttr(attr.SuperClassName);
			else
				break;
		}
		Integer id=0,tid=0;
		try {
			attr=al.pop();
		} catch (Exception e) {
			attr=null;
		}
		while(attr!=null)
		{
			tid=Insert(db,conn,attr);
			if(tid!=0)
				id=tid;
			try {
				attr=al.pop();
			} catch (Exception e) {
				attr=null;
			}
		}
		myLRU.add(this);
		return id;
	}
	private Integer Insert(DB db,Connection conn,ORMClassAttr attr) throws Exception
	{
		if(params==null)
			params=new LinkedList<Object>();
		String cl=null,vl=null;
		for(String s:attr.Fields.keySet())
		{
			if(myClassAttr.DBGenerateKey==s)
				continue;
			cl=utils.StringAdd(cl, ",", s);
			vl=utils.StringAdd(vl, ",", "?");
			Object v=utils.getFiledValue(this, s);
			Object ev=Encrypte(attr.ClsName, s, v);
			Object dv=db.TransValueFromJavaToDB(ev);
			
			params.offer(dv);
		}
				
		String sql="Insert Into "+attr.DBTableName+"("+cl+") Values ("+vl+")";
		Exec(conn,sql,params);
		if(attr.DBGenerateKey!=null)
		{
			Integer id=db.GetGeneratedKey(conn, attr.DBGenerateKey);
			utils.setFiledValue(this, myClassAttr.DBGenerateKey, id);
			return id;
		}
		return 0;
	}
	
	public static boolean Exec(Connection conn,String sql,Queue<Object> param) throws Exception
	{
		
		utils.P(sql);
		
		PreparedStatement ps = conn.prepareStatement(sql);
		if(param!=null)
		{
			int len=param.size();
			for(int i=1;i<=len;i++)
			{
				Object obj=param.poll();								
				ps.setObject(i, obj);
			}
		}
		return ps.execute();
	}
	
	public String ToJSON() throws Exception
	{
		jxJson js=jxJson.GetObjectNode(myClassAttr.ClsName);
		ORMClassAttr attr=myClassAttr;
		while(attr!=null)
		{
			for(String s:attr.Fields.keySet())
			{
				jxJson sub=js.GetSubObject(s);
				if(sub==null)
					js.AddValue(s, utils.getFiledValue(this, s));
			}
			attr=getSuperClassAttr(myClassAttr.ClsName);
		}
		return js.TransToString();
	}
	public static jxORMobj GetFromJSON(jxJson js) throws Exception
	{
		if(js==null)return null;
		ORMClassAttr attr=getClassAttr(js.getName());
		if(attr==null)return null;
		jxORMobj obj=New(attr.clsType);
		for(jxJson sub:js)
		{
			FieldAttr fa = attr.Fields.get(sub.getName());
			if(utils.GetClassName(fa.FieldType)=="UUID")
				utils.setFiledValue(obj, sub.getName(),utils.TransToUUID((String) sub.getValue()));
			else
				utils.setFiledValue(obj, sub.getName(), utils.TransTo(fa.FieldType, sub.getValue()));
		}
		return obj;
	}
	
	//扩展属性的处理
	protected String getExtendValue(String FieldName,String Purpose) throws Exception
	{
		jxJson js=null;
		String spv=(String) utils.getFiledValue(this, FieldName);
		if(spv!=null)
			js=jxJson.JsonToObject(spv);
		else
			js=jxJson.GetObjectNode(FieldName);
		jxJson sub=js.GetSubObject(Purpose);
		if(sub!=null)
			return (String) sub.getValue();
		return null;
	}
	protected void setExtendValue(String FieldName,String Purpose,Object value) throws Exception
	{
		jxJson js=null;
		String spv=(String) utils.getFiledValue(this, FieldName);
		if(spv!=null)
			js=jxJson.JsonToObject(spv);
		else
			js=jxJson.GetObjectNode(FieldName);
		jxJson sub=js.GetSubObject(Purpose);
		if(sub!=null)
			sub.setValue(value);
		else
			js.AddValue(Purpose, value);
		utils.setFiledValue(this, FieldName,js.TransToString());
	}

	//获取通用信息
	static FieldAttr getFieldAttr(String ClassName,String FieldName)
	{
		ORMClassAttr attr=getClassAttr(ClassName);
		if(attr!=null)
			return attr.Fields.get(FieldName);
		return null;
	}
	static String GetClassName(String ClassName,String ColName)
	{
		ORMClassAttr attr=getClassAttr(ClassName),p=null;
		while(attr!=null)
		{
			FieldAttr f=attr.Fields.get(ColName);
			if(f!=null)
				p=attr;
			if(attr.SuperClassName!=null)
				attr=getClassAttr(attr.SuperClassName);
			else				
				attr=null;
		}
		if(p!=null)
			return p.ClsName;
		return null;
	}
	static ORMClassAttr getClassAttr(String ClassName)
	{
		return ClassAttrTree.get(ClassName);
	}
	static ORMClassAttr getClassAttr(Class<?> cls)
	{
		return ClassAttrTree.get(utils.GetClassName(cls));
	}
	static ORMClassAttr getSuperClassAttr(String ClassName)
	{
		ORMClassAttr attr = ClassAttrTree.get(ClassName);
		if(attr!=null&&attr.SuperClassName!=null)
			return ClassAttrTree.get(attr.SuperClassName);
		return null;
	}

	
	protected void DualMsg(jxMsg msg)
	{
		
	}
	
}

class FieldAttr
{
	Class<?> FieldType=null;
	boolean IsEnum=false;
	boolean  Encrypted=false;
	boolean IsPrimaryKey=false;
	boolean IsDBGenerateKey=false;
}
class ORMClassAttr
{
	String ClsName=null;
	Class<?> clsType=null;
	String DBTableName=null;
	String SuperClassName=null;
	String DBGenerateKey=null;
	ArrayList<String> PrimaryKeys=null;
	jxLink<Integer,ArrayList<String>> Indexs=null;
	Map<String,FieldAttr> Fields=new HashMap<String,FieldAttr>();
	
	
}