
package cn.ijingxi.common.app;

import java.util.Date;

import cn.ijingxi.common.orm.*;
import cn.ijingxi.common.orm.ORM.KeyType;

public class Container extends jxORMobj
{	
	public static void Init() throws Exception{	InitClass(Container.class);}
	public static void CreateDB() throws Exception
	{
		CreateTableInDB(Container.class);
	}
	
	@ORM(keyType=KeyType.AutoGenerated)
	public int ID;

	//@ORM(Index=1,Descr="顶层空间名")
	//public String SpaceName;

	@ORM(Index=1,Encrypted=true)
	public String Name;		

	//1-people
	//2-组织
	@ORM(Index=2,Descr="容器类型：1是顶层空间名、2是people、3是组织（隶属于顶层空间）、4是流程、5是流程实例等等")
	public int ContainerType;
	
	@ORM(Descr="json格式的附加信息",Encrypted=true)
	public String Addition;

	@ORM(Descr="说明信息",Encrypted=true)
	public String Descr;
	
	@ORM(Index=2,Descr="用于两者之间的同步")
	public Date CreateTime;		

	@ORM(Descr="频率")
	public int Frequency;
	
	
	
	
}