
package cn.ijingxi.common.app;

import java.util.Date;
import java.util.UUID;

import cn.ijingxi.common.Process.IExecutor;
import cn.ijingxi.common.orm.*;
import cn.ijingxi.common.orm.ORM.KeyType;
import cn.ijingxi.common.util.jxCompare;

public class Container extends jxORMobj implements IExecutor
{	
	public static final int ContainerType_TopSpace=1;
	public static final int ContainerType_People=2;
	public static final int ContainerType_Organize=3;
	public static final int ContainerType_Circle=4;
	public static final int ContainerType_Process=5;
	public static final int ContainerType_ProcessInstance=6;
	public static final int ContainerType_ProcessNode=7;
	public static final int ContainerType_Role=8;

	
	protected Container() throws Exception {
		super();
		CreateTime=new Date();
	}
	public static void Init() throws Exception{	InitClass(Container.class);}
	public static void CreateDB() throws Exception
	{
		CreateTableInDB(Container.class);
	}
	
	@ORM
	public String TypeName;
	
	@ORM(keyType=KeyType.AutoGenerated)
	public int ID;
	
	@ORM(Index=1,Descr="用于人、组织等的全局确定")
	public UUID UniqueID;	
	public static Container getByUniqueD(UUID uuid) throws Exception
	{
		SelectSql s=new SelectSql();
		s.AddTable("Container");
		s.AddContion("Container", "UniqueID", jxCompare.Equal, uuid);
		Container c=(Container) Get(Container.class,s);
		if(c!=null)
			return (Container) GetByID(c.TypeName,c.ID);
		return null;
	}
	public static UUID getUniqueID(Integer ContainerID) throws Exception
	{
		SelectSql s=new SelectSql();
		s.AddTable("Container");
		s.AddContion("Container", "ID", jxCompare.Equal, ContainerID);
		Container c=(Container) Get(Container.class,s);
		if(c!=null)
			return ((Container) GetByID(c.TypeName,c.ID)).UniqueID;
		return null;
	}
	
	@ORM(Index=2,Descr="用于隔离不同的组织、圈子等等")
	public int TopSpaceID;

	@ORM(Index=3,Encrypted=true)
	public String Name;		

	//1-people
	//2-组织
	@ORM(Index=4,Descr="容器类型：1是顶层空间名、2是people、3是组织（隶属于顶层空间）、4是流程、5是流程实例等等")
	public int ContainerType;
	
	@ORM(Descr="说明信息",Encrypted=true)
	public String Descr;
	
	@ORM(Index=5,Descr="用于两者之间的同步")
	public Date CreateTime;


	@Override
	public ORMID GetID() throws Exception {
		return super.GetID();
	}
	@Override
	public UUID GetOwnerID() {
		return null;
	}
	@Override
	public IExecutor GetRealExecutor() {
		return this;
	}
	@Override
	public String getName() {
		return Name;
	}
	@Override
	public UUID getUniqueD() {
		return UniqueD;
	}		

	
	
	
}