
package cn.ijingxi.common.app;

import java.util.*;

import cn.ijingxi.common.Process.*;
import cn.ijingxi.common.orm.*;
import cn.ijingxi.common.orm.ORM.KeyType;
import cn.ijingxi.common.util.*;

public class jxSystem extends jxORMobj
{	
	public static final UUID zeroUUID=UUID.fromString("00000000-0000-0000-0000-000000000000");
	public static final UUID broadUUID=UUID.fromString("11111111-1111-1111-1111-111111111111");

	public static void Init() throws Exception{	InitClass(jxSystem.class);}	
	public static void CreateDB() throws Exception
	{
		CreateTableInDB(jxSystem.class);
		CreateTableInDB(People.class);
		jxSystem s=(jxSystem) jxORMobj.New(jxSystem.class);
		s.SystemUUID=UUID.randomUUID();
		s.Insert();
		People p=(People) jxORMobj.New(People.class);;
		//1号是手机主人，但如果某人在两台手机上都装了，则会出现冲突，需要加以解决
		p.PeopleID=s.SystemUUID;
		p.Insert();
	}
	
	public static jxSystem getSystem() throws Exception
	{
		return (jxSystem) GetByID(jxSystem.class,1);
	}
	
	@ORM(keyType=KeyType.AutoGenerated)
	public int ID;

	@ORM
	public Date MainSyncTime;
	
	@ORM
	public UUID SystemUUID;

	//用{}框起来的字符串Purpose（流水号用在哪，如流程名）、Name（当前请求者的姓名）YYYY、MM、DD或YYYYMMDD、SND4（4位日流水）、
	//SNT8（8位总流水）之类
	//如：{Purpose}-{Name}-{YYYYMMDD}-{SND3}，将产生：报销-徐晓轶-20150120-003
	@ORM(Descr="json格式的流水号模板")
	public String SNModel;
	@ORM(Descr="json格式的日流水号数字")
	public String SNDayNumber;
	@ORM(Descr="json格式的总流水号数字")
	public String SNTotalNumber;
	@ORM(Descr="json格式的流水号产生时的日期")
	public String SNLastDate;

	@ORM(Descr="json格式的附加信息")
	public String Addition;
		
	private static Map<String,SN> SNTree=new HashMap<String,SN>();
	
	public String GetSN(String Purpose,IExecutor caller) throws Exception
	{
		SN sn=SNTree.get(Purpose);
		if(sn==null)
		{
			String m=getExtendValue(SNModel,Purpose);
			if(m==null)
				throw new Exception(Purpose+"未设置流水号！！");
			String dn=getExtendValue(SNDayNumber,Purpose);
			String tn=getExtendValue(SNTotalNumber,Purpose);
			String dt=getExtendValue(SNLastDate,Purpose);
			sn=new SN(Purpose,m,utils.TransToDate(dt));
			sn.Number=utils.TransToInteger(dn);
			sn.TatolNumber=utils.TransToInteger(tn);
			SNTree.put(Purpose, sn);
		}
		return sn.GetNumber(caller);
	}
	
	public void AddSNModel(String Purpose,String Model) throws Exception
	{
    	setExtendValue(SNModel,Purpose,Model);
	}
	
}
